### ISSUE TITLE
[REDACTED] ru

### ISSUE THREAD

**Issue by Horodep** [justrealmilk/braytech.org-translations#119]
Совсем не нравится перевод [REDACTED] как [УДАЛЕНО]. Предлагаю заменить на [ЗАСЕКРЕЧЕНО]. Да, я понимаю, что официальная локализация [УДАЛЕНО].

Don't like translation [REDACTED] as [УДАЛЕНО]. Suggest changing it to [ЗАСЕКРЕЧЕНО]. Yes, I realise [УДАЛЕНО] is official localization.

**Comment by Horodep** [comment]
@blackjetcat would appreciate discussion

**Comment by blackjetcat** [comment]
I will probably go with official translation, because Braytech trying to be close to the official game UI, and I think that translation should follow the same path.
