### ISSUE TITLE
Views.Weeklies.Description ru

### ISSUE THREAD

**Issue by Horodep** [justrealmilk/braytech.org-translations#120]
Так же не нравится:
"Guardian's guide to weekly rituals with tips for prestige and triumph"
"Гайд Стража по еженедельным активностям с подсказками по триумфам и испытаниям"

**Comment by Horodep** [comment]
Horodep:

> is just your sense of humor or there is something behind prestige?

Tom Chapman ответил(а) Horodep:

> I think raid challenges are prestigious

**Comment by Horodep** [comment]
@blackjetcat would appreciate help)

**Comment by blackjetcat** [comment]
I think that it will be better like that - "Руководство для стражей" and not "Гайд для стражей", don't see any other issues here. And also I don't see how "prestige" can be translated without losing it's sense in Russian or it can make it too long
